# Generated by Django 2.0 on 2018-02-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age_estimation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='average',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='frequency2',
            field=models.FloatField(default=100),
        ),
    ]
