# Generated by Django 2.0 on 2018-02-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age_estimation', '0002_auto_20180213_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
